menu:
  - name: Home 
    directory: /
    icon: icon-home
  - name: Books
    directory: /books
    icon: icon-book
  - name: Archives
    directory: /archives
    icon: icon-archive
  - name: About
    directory: /about
    icon: icon-user

# duoshuo comment
duoshuo: ture
duoshuo_name: mattshma

# disqus comment
disqus: false
disqus_shortname: 

# google analytics
googleTrackId: 

is_donate: true
donate:
  wechat: ../../../../images/donate/wechat.jpg
  alipay: ../../../../images/donate/alipay.jpg
donate_text: "欣赏此文？你可以打赏我，这会更鼓励我创作~！"
